version: '3.7'

services:
      
      pgrass-jobs:
        build: .
        hostname: pgrass-jobs
        container_name: pgrass-jobs
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        volumes:
          - 'pgrass-data-jobs:/APP'
          - 'pgrass-share:/data'
          - '/etc/localtime:/etc/localtime'

volumes:
  pgrass-data-jobs:
  pgrass-share:
