version: '3.7'

services:
      
      pgrass-jobs-dev:
        build: .
        hostname: pgrass-jobs-dev
        container_name: pgrass-jobs-dev
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        volumes:
          - '../:/APP/pgrass-jobs'
          - './data/:/data'
          - '/etc/localtime:/etc/localtime'
          - './.env:/APP/.env'
