name: Push
on: [push]

jobs:
  code-security:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.4]
        poetry-version: [1.1.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run safety
        run: poetry run safety check
      - name: Run pip-audit
        run: poetry run pip-audit
